server:
    # 服务器的HTTP端口，默认为8080
    port: 18080
ruoyi:
    # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
    profile: D:/poor/uploadPath
# 数据源配置
spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://81.70.179.86:13306/lms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: Qwe123!@#
    data:
        # redis 配置
        redis:
            # 地址
            host: 81.70.179.86
            # 端口，默认为6379
            port: 16379
            # 数据库索引
            database: 2
            # 密码
            password: qwe123-=
    ai:
        dashscope:
            api-key: sk-ddee32b3167f437cb9e6a3f1dc886bb9